
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'  # Autoriser un mot de passe vide
      MYSQL_DATABASE: gestion_examens     # Nom de la base de données
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: